### ISSUE TITLE
clicking on save as or save does nothing

### ISSUE THREAD

**Issue by popdynamite5511** [hdfsyu/pingpad#1]
self explanitory
fix plz

**Comment by hdfsyu** [comment]
There is nothing wrong with the project, can you please try running it with the command python3 and send me the output?

**Comment by hdfsyu** [comment]
Since it works for me I am guessing there is nothing wrong

**Comment by popdynamite5511** [comment]
Its probably just a macos thing i presume then. (btw theres no error outputs or anything)

**Comment by hdfsyu** [comment]
Since there is no problem with the project, I am going to close this issue now.
